sudo: required
dist: trusty
language: python
node_js:
  - "8.10"
python:
  - "3.6"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
before_install:
  - nvm install 8.10
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - python3 -V
  - pip3 -V
install:
  - npm install
  - pip3 install -r requirements.txt
script: ./bin/test
env:
  global:
    - CXX=g++-4.8
    - NODE_ENV=development
branches:
  - release
  - test